"""add created_at in postlike model

Revision ID: 0d61175f0bb8
Revises: f6127ea6b67f
Create Date: 2023-07-25 12:23:35.474644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d61175f0bb8'
down_revision = 'f6127ea6b67f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('postlike', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('postlike', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
