"""add index

Revision ID: aad702551d24
Revises: 0d61175f0bb8
Create Date: 2023-07-26 19:47:21.288977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aad702551d24'
down_revision = '0d61175f0bb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
